name: Test

on:
  push:
    branches:
    - master
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Setup poetry
      id: poetry_setup
      uses: ItsDrike/setup-poetry@v1
      with:
          working-dir: ./backend
          python-version: ${{ matrix.python-version }}
          install-args: --with github_hooks --sync

    - name: Download CSV tables
      run: |
        mkdir parser/data
        cd parser/data

        curl https://files.perchun.it/ssps/2023it.csv -Lo 2023it.csv

        # verify signatures of files
        echo 'f8e4a840b9a15306d5f37484e342d75f101f79a85c082650f132a74e229f909a  2023it.csv' | sha256 -c

    - name: Generate DB using parser
      run: |
        cd parser
        python -m src data/2023it.csv 2023 it ../backend/data

    - name: Run tests
      run: |
        cd backend
        make test
